version: "3.9"
services:
  api:
    container_name: api
    build:
      context: .
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    command: yarn start:debug
    ports:
      - 3000:3000
      - 9229:9229